version: '3'

env:
  BIN_NAME: 'torr-helper'
  ENTRY: 'cmd/main.go'
  BIN_DIR: bin
  PLATFORM_GOOS:
    sh: go env GOOS
  PLATFORM_GOARCH:
    sh: go env GOARCH
  DOCKER_IMAGE_TAG: yae-registry.cr.cloud.ru/torr-helper:latest

tasks:
  build:
    vars:
      GOARCH: '{{ default .PLATFORM_GOARCH .GOARCH}}' 
      GOOS: '{{ default .PLATFORM_GOOS .GOOS}}'
      SUFFIX: '{{default "" .SUFFIX}}'
    cmds:
      - GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build -v -o ${BIN_DIR}/${BIN_NAME}_{{.GOARCH}}{{.SUFFIX}} {{.ENTRY}}
  
  build-win:
    cmds:
      - task: build
        vars: { SUFFIX: '.exe'}
        silent: true
  
  build-linux2:
    vars:
      GOOS: linux
    cmds:
      - for: ['amd64', 'arm64']
        task: build
        vars: {GOOS: '{{.GOOS}}', GOARCH: '{{.ITEM}}'}

  build-linux:
    env:
      GOOS: linux
    cmds: 
      - for: ['amd64', 'arm64']
        cmd: GOARCH={{ .ITEM }} go build -v -o ${BIN_DIR}/${BIN_NAME}_linux_{{ .ITEM }} {{ .ENTRY}}

  build-image:
    cmds:
      - docker build -t {{.DOCKER_IMAGE_TAG}} .
  
  publish-image:
    deps: [build-image]
    cmds:
      - docker push {{.DOCKER_IMAGE_TAG}}
  run:
    cmds:
      - go run {{ .ENTRY }} config.toml
  
  env:
    cmds:
      - echo $PLATFORM_GOOS
